In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("array:",arr)
print("shape:",arr.shape)




array: [1 2 3 4 5 6]
shape: (6,)


In [3]:
import numpy as np
arr=np.arange(0,10,2)
print("array:",arr)

array: [0 2 4 6 8]


In [13]:
import numpy as np
arr=np.linspace(0,1,5)
print("array:",arr)

array: [0.   0.25 0.5  0.75 1.  ]


In [11]:
import numpy as np
arr=np.zeros((2,3))
print("array of zeros:\n",arr)

array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np
arr=np.asarray([1,2,3,4,5])
print("array using asarray:",arr)

array using asarray: [1 2 3 4 5]


In [14]:
import numpy as np
arr=np.ones((3,4))
print("array of ones:\n",arr)

array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6,])
reshaped=arr.reshape(2,3)
print("reshaped array:\n",reshaped)

reshaped array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr=np.copy(np.array([1,2,3,4,5]))
print("copied array:",arr)

copied array: [1 2 3 4 5]


In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("mean:",np.mean(arr))

mean: 3.5


In [26]:
import numpy as np
arr=np.array([4,9,16,25])
print("sqrt:",np.sqrt(arr))

sqrt: [2. 3. 4. 5.]


In [27]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("add:",np.add(arr1,arr2))

add: [5 7 9]


In [33]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])    
dot=np.dot(a,b.T)
print("dot product:\n",dot)

dot product:
 [[ 50  68]
 [122 167]]


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("original array:\n",arr)

original array:
 [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr_3D=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array:\n",arr_3D)


3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
